'use client';
import { Pregunta } from './Encuesta';

export const preguntasPorSeccion: { titulo: string; preguntas: Pregunta[]; }[] = [
    {
        titulo: 'RH y Productividad',
        preguntas: [
            { id: 'nombre_encuestador', texto: 'Nombre del encuestador', tipo: 'texto' },
            { id: 'pregunta_01', texto: 'Bitácoras de acceso a unidad', tipo: 'checkbox' },
            { id: 'pregunta_02', texto: 'Porcentaje del personal en turno que se encuentra en este momento en la unidad', tipo: 'texto' },
            { id: 'pregunta_03', texto: 'Porcentaje del personal del turno que se encuentra en su área de trabajo haciendo las actividades que le corresponden', tipo: 'texto' },
            { id: 'pregunta_04', texto: 'El personal porta gafete visible', tipo: 'checkboxdual' },
            { id: 'pregunta_05', texto: 'Productividad de consulta reportada de los últimos 2 meses', tipo: 'texto' },
            { id: 'pregunta_06', texto: 'Reloj checador', tipo: 'checkboxdual' },
            { id: 'pregunta_07', texto: 'Carpeta de expediente de recursos humanos', tipo: 'checkboxdual' },
            { id: 'pregunta_08', texto: 'Electrocardiogramas realizados en bitácora en los últimos 2 meses', tipo: 'texto' },
        ],
    },
    {
        titulo: 'Mantenimiento y otras condiciones de la unidad',
        preguntas: [
            { id: 'supervisor_01', texto: 'Nombre de responsable de unidad', tipo: 'texto' },
            { id: 'pregunta_09', texto: 'Accesible para personas con discapacidad y adultos mayores (rampas, barandal, etc.).', tipo: 'checkboxdual' },
            { id: 'pregunta_10', texto: 'Condiciones exteriores de infraestructura', tipo: 'checkboxquint' }, //Aqui es 0-5
            { id: 'pregunta_11', texto: 'Correcto registro de reportes en plataforma de mantenimiento', tipo: 'checkbox' },
            { id: 'pregunta_12', texto: 'Equipos de cómputo suficientes y funcionales', tipo: 'checkbox' },
        ],
    },
    {
        titulo: 'Primer contacto con px (Agenda)',
        preguntas: [
            { id: 'supervisor_02', texto: 'Nombre de personal de supervisión de primer contacto', tipo: 'texto' },
            { id: 'pregunta_13', texto: 'Entre 3 y 6 citados por núcleo por turno', tipo: 'checkboxdual' },
            { id: 'pregunta_14', texto: 'Citas cada 30 min', tipo: 'checkboxdual' },
            { id: 'pregunta_15', texto: 'Buen registro de citados y abiertas intercalados, quienes acudieron y los que no', tipo: 'checkbox' },
            { id: 'pregunta_16', texto: 'Coinciden px en agenda (que llegaron) con hoja diaria médica', tipo: 'checkbox' },
        ],
    },
    {
        titulo: 'Sala de espera',
        preguntas: [
            { id: 'pregunta_17', texto: 'Con techo adecuado y tamaño adecuado', tipo: 'checkboxdual' },
            { id: 'pregunta_18', texto: 'Bancas en buen estado', tipo: 'checkboxdual' },
            { id: 'pregunta_19', texto: 'Los pacientes la utilizan', tipo: 'checkboxdual' },
            { id: 'pregunta_20', texto: 'Cuenta con baños abiertos para pacientes H/M', tipo: 'checkbox' },
            { id: 'pregunta_21', texto: 'Sanitas y jabón', tipo: 'opcional' },
            { id: 'pregunta_22', texto: 'Agua', tipo: 'opcional' },
            //Preguntas opcionales
        ],
    },
    {
        titulo: 'Somatometría',
        preguntas: [
            { id: 'supervisor_03', texto: 'Nombre de Enfermera de supervisión', tipo: 'texto' },
            { id: 'pregunta_23', texto: 'Báscula con estadímetro', tipo: 'checkboxdual' },
            { id: 'pregunta_24', texto: 'Báscula pesa bebé', tipo: 'checkboxdual' },
            { id: 'pregunta_25', texto: 'Pesas patrón', tipo: 'checkboxdual' },
            { id: 'pregunta_26', texto: 'Hoja diaria de enfermería', tipo: 'checkbox' },
            { id: 'pregunta_27', texto: 'Termómetro', tipo: 'checkboxdual' },
            { id: 'pregunta_28', texto: 'Glucómetro', tipo: 'checkboxdual' },
            { id: 'pregunta_29', texto: 'Esfigmomanómetro', tipo: 'checkboxdual' },
            { id: 'pregunta_30', texto: 'Estetoscopio', tipo: 'checkboxdual' },
            { id: 'pregunta_31', texto: 'Oxímetro', tipo: 'checkboxdual' },
            { id: 'pregunta_32', texto: 'Tiras para glicemia', tipo: 'checkboxdual' },
            { id: 'pregunta_33', texto: 'Cinta de perímetro cefálico', tipo: 'checkboxdual' },
            { id: 'pregunta_34', texto: 'Cinta de perímetro abdominal', tipo: 'checkboxdual' },
            { id: 'pregunta_35', texto: 'Pruebas de VIH, VDRL', tipo: 'checkboxdual' },
            { id: 'pregunta_36', texto: 'Cardiocheck con tiras', tipo: 'checkboxdual' },
            { id: 'pregunta_37', texto: 'Sello de  RCV', tipo: 'checkboxdual' },
            { id: 'pregunta_38', texto: 'Prueba con tiras de HbA1C', tipo: 'checkboxdual' },
            { id: 'pregunta_39', texto: 'Bote de RPBI', tipo: 'checkboxdual' },
            { id: 'pregunta_40', texto: 'Tiras urobililabstix', tipo: 'checkboxdual' },
            { id: 'pregunta_41', texto: 'Bitácora de mantenimiento  prev de equipo', tipo: 'checkbox' },
            { id: 'pregunta_42', texto: 'Bitácora de calibración de básculas', tipo: 'checkbox' },
        ],
    },
    {
        titulo: 'Curaciones',
        preguntas: [
            { id: 'pregunta_43', texto: 'Instrumental estéril con fecha vigente', tipo: 'checkboxdual' },
            { id: 'pregunta_44', texto: 'Esterilizador funcional', tipo: 'checkbox' },
            { id: 'pregunta_45', texto: 'Insumos presentes y semaforizados', tipo: 'checkbox' },
            { id: 'pregunta_46', texto: 'Mesa pasteur', tipo: 'checkboxdual' },
            { id: 'pregunta_47', texto: 'Mesa mayo', tipo: 'checkboxdual' },
            { id: 'pregunta_48', texto: 'Espejos vaginales, chico, mediano y grande', tipo: 'checkbox' },
            { id: 'pregunta_49', texto: 'Espátulas', tipo: 'checkboxdual' },
            { id: 'pregunta_50', texto: 'Batas', tipo: 'checkboxdual' },
            { id: 'pregunta_51', texto: 'Formato muestra papanicolau', tipo: 'checkboxdual' },
            { id: 'pregunta_52', texto: 'Cepillo citológico', tipo: 'checkboxdual' },
            { id: 'pregunta_53', texto: 'Laminillas', tipo: 'checkboxdual' },
            { id: 'pregunta_54', texto: 'Fijador o alcohol', tipo: 'checkboxdual' },
            { id: 'pregunta_55', texto: 'Guantes chicos y medianos', tipo: 'checkbox' },
            { id: 'pregunta_56', texto: 'Lámpara de examinación funcional', tipo: 'checkboxdual' },
            { id: 'pregunta_57', texto: 'Bitácora seg displasias', tipo: 'checkbox' },
            { id: 'pregunta_58', texto: 'Bitácora de proceso de esterilización', tipo: 'checkbox' },
            { id: 'pregunta_59', texto: 'Mesa de exploración con pierneras', tipo: 'checkbox' },
            { id: 'pregunta_60', texto: 'VSO, Jarra y cuchara', tipo: 'checkboxdual' },
            { id: 'pregunta_61', texto: 'Cinta testigo', tipo: 'checkboxdual' },
            { id: 'pregunta_62', texto: 'Frascos de antisépticos con fecha vigente', tipo: 'checkboxdual' },
        ],
    },
    {
        titulo: 'Preventiva',
        preguntas: [
            { id: 'pregunta_63', texto: 'Refrigerador 18 pies puerta acero inoxidable', tipo: 'checkboxdual' },
            { id: 'pregunta_64', texto: 'Termómetro de vástago', tipo: 'checkboxdual' },
            { id: 'pregunta_65', texto: 'Termómetro tipo pluma', tipo: 'checkboxdual' },
            { id: 'pregunta_66', texto: 'No dar citas (excepto BCG)', tipo: 'checkbox' },
            { id: 'pregunta_67', texto: 'Bitácora de calibración de termómetros', tipo: 'checkbox' },
            { id: 'pregunta_68', texto: 'Existencia de esquema básico (Vacunas)', tipo: 'checkboxquad' }, //4 rango
            { id: 'pregunta_69', texto: 'Lancetas para tamiz', tipo: 'checkboxdual' },
            { id: 'pregunta_70', texto: 'Papel filtro', tipo: 'checkboxdual' },
            { id: 'pregunta_71', texto: 'Bitácora limpieza refri', tipo: 'checkbox' },
            { id: 'pregunta_72', texto: 'Bitácora tamiz', tipo: 'checkbox' },
            { id: 'pregunta_73', texto: 'Vaso contenedor o rejilla', tipo: 'checkboxdual' },
            { id: 'pregunta_74', texto: 'Jeringas', tipo: 'checkboxdual' },
            { id: 'pregunta_75', texto: 'Torundas', tipo: 'checkboxdual' },
            { id: 'pregunta_76', texto: 'Cartillas de vacunación', tipo: 'checkboxdual' },
            { id: 'pregunta_77', texto: 'Termo de 9 litros', tipo: 'checkboxdual' },
            { id: 'pregunta_78', texto: 'Paquetes congelantes', tipo: 'checkboxdual' },
            { id: 'pregunta_79', texto: 'Botes de RPBI', tipo: 'checkboxdual' },
            { id: 'pregunta_80', texto: 'Bitácora de temperatura refrigerador', tipo: 'checkbox' },
            { id: 'pregunta_81', texto: 'Bitácora de productividad', tipo: 'checkbox' },
        ],
    },
    {
        titulo: 'Farmacia',
        preguntas: [
            { id: 'supervisor_04', texto: 'Nombre del responsable de Farmacia', tipo: 'texto' },
            { id: 'pregunta_82', texto: 'Termohigrómetro', tipo: 'checkboxdual' },
            { id: 'pregunta_83', texto: 'Medicamentos lasa y alto riesgo', tipo: 'checkbox' },
            { id: 'pregunta_84', texto: 'Semaforización y orden medicamentos y material de curación', tipo: 'checkbox' },
            { id: 'pregunta_85', texto: 'Con lector óptico', tipo: 'checkboxdual' },
            { id: 'pregunta_86', texto: 'Congruencia fisica y en sistema de 10 claves de medicamentos y 5 de material de curación', tipo: 'texto' },
            { id: 'pregunta_87', texto: 'SIAM actualizado', tipo: 'checkboxdual' },
            { id: 'pregunta_88', texto: 'Archivos simed max 3 días de retraso', tipo: 'checkboxdual' },
            { id: 'pregunta_89', texto: 'Con computadora o computadora accesible a todo médico', tipo: 'checkboxdual' },
        ],
    },
    {
        titulo: 'Consultorio',
        preguntas: [
            { id: 'supervisor_05', texto: 'Médico a evaluar', tipo: 'texto' },
            { id: 'pregunta_90', texto: 'Escritorio', tipo: 'checkboxdual' },
            { id: 'pregunta_91', texto: 'Silla fija acojinada (2)', tipo: 'checkbox' },
            { id: 'pregunta_92', texto: 'Mesa de exploración', tipo: 'checkboxdual' },
            { id: 'pregunta_93', texto: 'Estuche de diagnóstico con pilas', tipo: 'checkbox' },
            { id: 'pregunta_94', texto: 'Estetoscopio', tipo: 'checkboxdual' },
            { id: 'pregunta_95', texto: 'Fonodetector o estetoscopio de pinard', tipo: 'checkboxdual' },
            { id: 'pregunta_96', texto: 'Martillo percutor', tipo: 'checkboxdual' },
            { id: 'pregunta_97', texto: 'Monofilamento', tipo: 'checkboxdual' },
            { id: 'pregunta_98', texto: 'Mesa mayo', tipo: 'checkboxdual' },
            { id: 'pregunta_99', texto: 'Escalerilla de 2 peldaños', tipo: 'checkboxdual' },
            { id: 'pregunta_100', texto: 'Luz y ventilacion adecuada', tipo: 'checkboxdual' },
            { id: 'pregunta_101', texto: 'Lámpara de examinación', tipo: 'checkboxdual' },
        ],
    },
    {
        titulo: 'Referencia y contrareferencia',
        preguntas: [
            { id: 'pregunta_102', texto: 'Verificar 3 expedientes clínicos que la referencia y contrareferencia se hayan realizado de manera correcta', tipo: 'checkboxquint' }, //5
        ],
    },
    {
        titulo: 'Calculadora de acciones preventivas', // realizar 2 veces
        preguntas: [
            { id: 'pregunta_103', texto: 'Número de acciones recomendadas por la calculadora de Acciones Preventivas ', tipo: 'texto' },
            { id: 'pregunta_104', texto: 'De cuántas de las acciones recomendadas hay evidencia de que se hayan cumplido en la periodicidad indicada ', tipo: 'texto' },
            { id: 'pregunta_105', texto: 'De las acciones recomendadas, cuántas requieren seguimiento por resultados anormales', tipo: 'texto' },
            { id: 'pregunta_106', texto: 'A cuántas de éstas se le ha dado seguimiento', tipo: 'texto' },
        ],
    },
    {
        titulo: 'Motivo de consulta',
        preguntas: [
            { id: 'expediente_01', texto: 'Expediente 1', tipo: 'selec' },
            { id: 'pregunta_108', texto: 'De acuerdo al algoritmo de manejo de paciente diabetico califique el manejo que se le ha dado a este paciente', tipo: 'exp1d' },
            { id: 'pregunta_107', texto: 'Correcta selección de fármacos', tipo: 'exp1d' },
            { id: 'pregunta_109', texto: 'Correcta selección de fármacos', tipo: 'exp1h' },
            { id: 'pregunta_110', texto: 'De acuerdo al algoritmo de manejo de paciente hipertenso califique el manejo que se le ha dado a este paciente', tipo: 'exp1h' },
            { id: 'pregunta_111', texto: 'Congruencia de Cuadro Clínico - Diagnostico - Tratamiento', tipo: 'checkboxdual' },
            { id: 'pregunta_112', texto: 'Nombre completo y fecha de nacimiento en todo documento', tipo: 'checkboxdual' },
            { id: 'pregunta_113', texto: 'Riesgo de Caídas', tipo: 'checkboxdual' },
            //IRAS
            { id: 'expediente_02', texto: 'Expediente 2', tipo: 'selec2' },
            { id: 'pregunta_114', texto: '¿Se recetó antibiótico?', tipo: 'exp2Ir' },
            { id: 'pregunta_115', texto: '¿El cuadro clínico justifica la respuesta de la pregunta anteriror?', tipo: 'exp2Ir' },
            { id: 'pregunta_116', texto: 'El antibiótico seleccionado fue adecuado para el padecimiento', tipo: 'exp2Ir' },
            { id: 'pregunta_117', texto: 'De acuerdo al manejo seleccionado ¿el esquema y posología es el adecuado?', tipo: 'exp2Ir' },
            //IVU
            { id: 'pregunta_118', texto: 'La paciente presenta: ', tipo: 'checkboxdualIVU' },
            { id: 'pregunta_119', texto: 'Correcto interrogatorio y estado de diagnóstico', tipo: 'exp2Iv' },
            { id: 'pregunta_120', texto: '¿Se recetó antibiótico?', tipo: 'exp2Iv' },
            { id: 'pregunta_121', texto: '¿El cuadro clínico justifica la respuesta de la pregunta anterior?', tipo: 'exp2Iv' },
            { id: 'pregunta_122', texto: 'El antibiótico seleccionado fue adecuado para el padecimiento', tipo: 'exp2Iv' },
            { id: 'pregunta_123', texto: 'De acuerdo al manejo seleccionado ¿el esquema y posología es el adecuado?', tipo: 'exp2Iv' },
            //GEPI
            { id: 'pregunta_124', texto: 'Uso racional de antibiótico', tipo: 'exp2Ge' },
            { id: 'pregunta_125', texto: 'Ciprofloxacimo/ metromidasol/ etc. esquema y poslogía', tipo: 'exp2Ge' },
            { id: 'pregunta_126', texto: 'De acuerdo al manejo seleccionado ¿el esquema y posología es el adecuado?', tipo: 'exp2Ge' },
            { id: 'pregunta_127', texto: 'Esquema Hidratacion', tipo: 'exp2Ge' },
            { id: 'pregunta_128', texto: 'Congruencia de Cuadro Clínico - Diagnostico - Tratamiento', tipo: 'checkboxdual' },
            { id: 'pregunta_129', texto: 'Nombre completo y fecha de nacimiento en todo documento', tipo: 'checkboxdual' },
            { id: 'pregunta_130', texto: 'Riesgo de Caídas', tipo: 'checkboxdual' },
            // EXP 3 Niño sano
            { id: 'expediente_03', texto: 'Expediente 3', tipo: 'selec3' },
            { id: 'pregunta_131', texto: 'Se evaluó el Desarrollo neurológico (hitos del desarrollo)', tipo: 'exp3N' },
            { id: 'pregunta_132', texto: 'Peso/talla', tipo: 'exp3N' },//texto
            { id: 'pregunta_133', texto: 'Peso/edad', tipo: 'exp3N' },
            { id: 'pregunta_134', texto: 'Talla/edad', tipo: 'exp3N' },
            //Embarazo
            { id: 'pregunta_135', texto: 'Se entregaron suplementos FE y acido fólico', tipo: 'exp3Em' },
            { id: 'pregunta_136', texto: 'Se registró la frecuencia cardiaca fetal ', tipo: 'exp3Em' },
            { id: 'pregunta_137', texto: '¿Es embarazada de alto riesgo o semana 36 o más?', tipo: 'exp3Em' }, //si, aparece la siguiente:
            { id: 'pregunta_137', texto: 'Referencia a las embarazadas de alto riesgo o en semana de gestacion 36', tipo: 'exp3Em' },

            { id: 'pregunta_138', texto: 'Congruencia de Cuadro Clínico Diagnostico Tratamiento', tipo: 'checkboxdual' },
            { id: 'pregunta_139', texto: 'Nombre completo y fecha de nacimiento en todo documento ', tipo: 'checkboxdual' },
            { id: 'pregunta_140', texto: 'Riesgo de caídas', tipo: 'checkboxdual' },
        ],
    },
    //Secciones
];
